spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pix?currentSchema=pix
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        use_second_level_cache: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
topic:
  request: pix_example_spring_template_topic
  reply: pix_example_spring_reply_topic

waitInSeconds: 5